[package]
name = "chagaller"
version = "0.1.0"
edition = "2021"

[dependencies]
askama = "0.12.1"
chrono = "0.4.38"
clap = { version = "4.5.17", features = ["derive"] }
image = "0.25.2"
rust-embed = "8.5.0"
